export enum RevenueType {
    SUBSCRIPTION = "SUBSCRIPTION",
    LICENSE = "LICENSE",
    USAGE_BASED = "USAGE_BASED",
    DIRECT_SALES = "DIRECT_SALES",
    FREEMIUM = "FREEMIUM",
    MARKETPLACE = "MARKETPLACE",
    ADVERTISING = "ADVERTISING",
    CONSULTING = "CONSULTING",
}
