export enum UserRoles {
    ADMIN = "ADMIN",
    DIRECTOR = "DIRECTOR",
    PROGRAM_MANAGER = "PROGRAM_MANAGER",
    COMMITTEE_MEMBER = "COMMITTEE_MEMBER",
    MENTOR = "MENTOR",
    APPLICANT = "APPLICANT",
    TEAM_MATE = "TEAM_MATE",
    FINANCE = "FINANCE",
    REVIEWER = "REVIEWER",
    NORMAL_USER = "NORMAL_USER",
}
